track_collection_homepage:
    path:     /
    defaults: { _controller: TrackCollectionBundle:Page:index }

tracks_list:
    path:     /api/tracks
    defaults: { _controller: TrackCollectionBundle:Track:get }
    requirements:
            method: GET
